# Generated by Django 4.0 on 2023-05-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('translate_info', models.CharField(max_length=300)),
                ('extra_info', models.CharField(max_length=300)),
                ('time', models.DateField()),
            ],
        ),
    ]
